### ISSUE TITLE
Error: enums must be represented as dicts or tuples

### ISSUE THREAD

**Issue by rconan** [birkenfeld/serde-pickle#12] opened 2021-02-02 18:32 UTC
I have the following:
```rust
use serde::{Deserialize,Serialize};
use serde_json;
use serde_pickle;
use std::fs::File;

#[derive(Debug, Deserialize, Serialize)]
pub struct Data {
    id: String,
    method: String,
    params: i32,
}
#[derive(Debug, Deserialize, Serialize)]
enum Message {
    Request(Data),
    Response(i32),
}

fn main() {
    let s = r#" {"Request": {"id": "u", "method": "q", "params": 1}} "#;
    let m: Message = serde_json::from_str(s).unwrap();
    println!("{:#?}", m);

    let mut file = File::create("examples/msg.pkl").unwrap();
    serde_pickle::to_writer(&mut file, &m, true).unwrap();

    let file = File::open("examples/msg.pkl").unwrap();
    let d: Message = serde_pickle::from_reader(file).unwrap();
    println!("{:#?}", d);
}
```
that allows to Serialize and Deserialize  `enum Message`.
If I load the pickle file in Python, I got the following representation
```python
('Request', {'id': 'u', 'method': 'q', 'params': 1})
```
now if I pickle the tuple in Python with:
```python
msg = ('Request', {'id': 'u', 'method': 'q', 'params': 1}) 
with open("pymsg.pkl","wb") as f: 
    pickle.dump(msg,f) 
```
and then Deserialize in Rust  with
```rust
    let file = File::open("examples/pymsg.pkl").unwrap();
    let d: Message = serde_pickle::from_reader(file).unwrap();
    println!("{:#?}", d);
```
I got the following error:
```rust
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(Structure("enums must be represented as dicts or tuples"))', examples/test_enum.rs:27:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Is it possible to Deserialize to a Rust enum from a Python pickled file?

**Comment by rconan** [comment] 2021-02-02 20:50
I found out that if I Deserialize in 2 steps
```rust
    let v: serde_pickle::Value = serde_pickle::from_reader(file).unwrap();
    let d: Message = serde_pickle::from_value(v).unwrap();
    println!("{:#?}", d);
```
there are no errors

**Comment by birkenfeld** [comment] 2021-02-03 08:02
Thanks for the report!  I could reproduce the bug and found that the cause is a MemoRef in the pickle.  I'll need to resolve that...

**Comment by birkenfeld** [comment] 2021-02-03 09:06
This should be fixed now. I'll release a bugfix version shortly.

**Closed as completed** 2021-02-03 09:05 UTC
